version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                name: Build documentation
                command: ./build_tools/circle/build_doc.sh
                timeout: "3600" # seconds
            - store_artifacts:
                path: docs/_build/html
            - add_ssh_keys:
                fingerprints:
                    - "bc:5b:f1:d9:0c:61:4a:47:6a:0e:f3:83:f1:ad:51:74"
            - deploy:
                name: Deploy documentation
                environment:
                    USERNAME: scaramallion
                    EMAIL: scaramallion@users.noreply.github.com
                command: ./build_tools/circle/push_doc.sh
