version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                name: Build documentation
                command: ./build_tools/circle/build_doc.sh
                timeout: "3600" # seconds
            - store_artifacts:
                path: docs/_build/html
            - add_ssh_keys:
                fingerprints:
                    - "98:5e:90:74:cf:f1:5a:c5:f3:b9:d5:98:72:30:8e:3c"
            - deploy:
                name: Deploy documentation
                environment:
                    USERNAME: scaramallion
                    EMAIL: scaramallion@users.noreply.github.com
                command: ./build_tools/circle/push_doc.sh
